[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "switchcraft"
version = "2025.12.4-beta"
description = "A universal silent switch finder and installer analyzer."
readme = "README.md"
authors = [{ name = "FaserF" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["installer", "silent-install", "automation", "winget", "msi", "exe"]
dependencies = [
    "pefile",
    "olefile",
    "requests",
    "click",
    "rich",
    "py7zr",
    "customtkinter",
    "tkinterdnd2",
    "pillow",
    "PyYAML"
]
requires-python = ">=3.9"

[project.scripts]
switchcraft = "switchcraft.main:cli"

[project.urls]
Homepage = "https://github.com/FaserF/SwitchCraft"
