[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "switchcraft"
version = "2026.1.2.dev0+9d07a00"
description = "A universal silent switch finder and installer analyzer."
readme = "README.md"
authors = [{ name = "FaserF" }]
license = "MIT"
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["installer", "silent-install", "automation", "winget", "msi", "exe"]
dependencies = [
    "pefile",
    "olefile",
    "requests",
    "click",
    "rich",
    "py7zr",
    "PyYAML",
    "keyring",
    "openai",
    "google-generativeai",
    "defusedxml",
    "PyJWT",
    "winotify"
]
requires-python = ">=3.9"

[project.optional-dependencies]
gui = [
    "customtkinter",
    "tkinterdnd2",
    "pillow",
    "plyer"
]
modern = ["flet>=0.80.1", "flet-desktop>=0.80.1", "flet-charts>=0.80.1"]
test = [
    "pytest>=7.0",
    "flet>=0.80.1",
    "flet-charts>=0.80.1"
]
build = [
    "pyinstaller==6.18.0"
]


[project.scripts]
switchcraft = "switchcraft.main:main"

[project.urls]
Homepage = "https://github.com/FaserF/SwitchCraft"

[tool.setuptools.package-data]
switchcraft = ["assets/**/*", "assets/lang/*.json"]
switchcraft_winget = ["utils/*.json"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
addopts = "--ignore=test_out.txt --ignore=test_output.txt --ignore=test_addons_result.txt"
