# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: FaserF.SwitchCraft
PackageVersion: 2025.12.10.0
InstallModes:
- silent
- silentWithProgress
UpgradeBehavior: install
Installers:
- Architecture: x86
  Scope: machine
  InstallerType: inno
  InstallerUrl: https://github.com/FaserF/SwitchCraft/releases/download/v2025.12.10/SwitchCraft-Setup.exe
  InstallerSha256: 903A2BE76671C22FBBC23CCA067B81053BFE2300339178CFD1BDB8BCDB470104
  InstallerSwitches:
    Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
    SilentWithProgress: /SILENT /SUPPRESSMSGBOXES /NORESTART
    InstallLocation: /DIR="<INSTALLPATH>"
    Log: /LOG="<LOGPATH>"
- Architecture: x86
  Scope: user
  InstallerType: inno
  InstallerUrl: https://github.com/FaserF/SwitchCraft/releases/download/v2025.12.10/SwitchCraft-Setup.exe
  InstallerSha256: 903A2BE76671C22FBBC23CCA067B81053BFE2300339178CFD1BDB8BCDB470104
  InstallerSwitches:
    Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
    SilentWithProgress: /SILENT /SUPPRESSMSGBOXES /NORESTART
    InstallLocation: /DIR="<INSTALLPATH>"
    Log: /LOG="<LOGPATH>"
- Architecture: x86
  InstallerType: portable
  InstallerUrl: https://github.com/FaserF/SwitchCraft/releases/download/v2025.12.10/SwitchCraft-windows.exe
  InstallerSha256: REPLACE_WITH_ACTUAL_SHA256_OF_PORTABLE_EXE
  Commands:
  - switchcraft
ManifestType: installer
ManifestVersion: 1.10.0
